var audioFileNames = ['Sound', 'Files',
'Recordings',
'Tracks',
'Music',
'Sounds',
'Podcasts',
'Voice Notes',
'Audios',
'Tunes',
'MP3s',
'Songs',
'Sound Bites'];

var videoFileNames = ['Films',
    'Clips',
    'Movies',
    'Footage',
    'Recordings',
    'Visuals',
    'Motion Pictures',
    'Videography',
    'Shorts',
    'Reels',
    'Montages'];
var imageFileNames = ['Pictures',
    'Photos',
    'Photographs',
    'Snapshots',
    'Stills',
    'Visuals',
    'Graphics',
    'Illustrations',
    'Thumbnails',
    'Icons',
    'Artworks',
    'Renderings'];